import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
<<<<<<< Updated upstream
    <html lang="en" data-theme="light">
      <body className={inter.className}>{children}</body>
=======
    <html lang="en">
      <body classNameName={inter.classNameName}>{children}</body>
>>>>>>> Stashed changes
    </html>
  );
}
